name: Go

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Config
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        touch account.go
        echo "package main

              var sshUser = $USER
              var sshPassword = $PASSWORD" >> account.go

        echo "cat account.go"
        cat account.go

        echo "ls -a ."
        ls -a .

        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}
      shell: bash

    - name: Show file content
      run: |
        cat account.go

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release -f .goreleaser.yaml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
