name: Go

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        printf ${{ secrets.CONFIG }} > account.go

    - name: Show file content
      run: |
        cat account.go

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release -f .goreleaser.yaml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
